apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet-web
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: page-web
        image: dddiallo/page_web
        ports:
        - containerPort: 80
